workers_dev = true
compatibility_date = "2024-09-22"

main = "build/worker/shim.mjs"
name = "axum-cloudflare-adapter"

[vars]
WORKERS_RS_VERSION = "0.4.0"

[build]
command = "cargo install -q worker-build && worker-build --release"
